---
- stat: path=/usr/sbin/etcd-{{version}}
  register: etcd

- get_url: url=https://github.com/coreos/etcd/releases/download/v{{version}}/etcd-v{{version}}-linux-amd64.tar.gz dest=/opt/etcd-v{{version}}-linux-amd64.tar.gz
  when: etcd.stat.exists == False

- file: path=/opt/etcd state=directory
  when: etcd.stat.exists == False

- unarchive: src=/opt/etcd-v{{version}}-linux-amd64.tar.gz dest=/opt/etcd/
  when: etcd.stat.exists == False

- copy: src=/opt/etcd/etcd-v{{version}}-linux-amd64/etcd dest=/usr/sbin/etcd-{{version}} mode=774 owner=root group=root
  when: etcd.stat.exists == False

- copy: src=/opt/etcd/etcd-v{{version}}-linux-amd64/etcdctl dest=/usr/sbin/etcdctl-{{version}} mode=774 owner=root group=root
  when: etcd.stat.exists == False

- file: src=/usr/sbin/etcd-{{version}} dest=/usr/sbin/etcd mode=774 owner=root group=root state=link

- file: src=/usr/sbin/etcdctl-{{version}} dest=/usr/sbin/etcdctl mode=774 owner=root group=root state=link

- file: path=/opt/etcd-v{{version}}-linux-amd64.tar.gz state=absent

- file: path=/opt/etcd state=absent

